package com.zanewnch.mybatismaven.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
1.
@Data is used to declare the class is a bean, and it would auto generate the getter and setter and equals and hashcode method

2. @NoArgsConstructor is used to declare the class is a bean, and it would auto generate the no-argument constructor

3.
@AllArgsConstructor is used to declare the class is a bean, and it would auto generate the constructor with all arguments
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    /*
    對應mysql的data type:

    int => Integer
    varchar => String
    tinyint => Short
     */
    private Integer id;
    private String name;
    private Short age;
    private Short gender;
    private String phone;

// the below code snippet is original generated by ptg plugin

//    public User() {
//    }
//
//    public User(Integer id, String name, Short age, Short gender, String phone) {
//        this.id = id;
//        this.name = name;
//        this.age = age;
//        this.gender = gender;
//        this.phone = phone;
//    }
//
//    /**
//     * 获取
//     *
//     * @return id
//     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * 设置
//     *
//     * @param id
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * 获取
//     *
//     * @return name
//     */
//    public String getName() {
//        return name;
//    }
//
//    /**
//     * 设置
//     *
//     * @param name
//     */
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    /**
//     * 获取
//     *
//     * @return age
//     */
//    public Short getAge() {
//        return age;
//    }
//
//    /**
//     * 设置
//     *
//     * @param age
//     */
//    public void setAge(Short age) {
//        this.age = age;
//    }
//
//    /**
//     * 获取
//     *
//     * @return gender
//     */
//    public Short getGender() {
//        return gender;
//    }
//
//    /**
//     * 设置
//     *
//     * @param gender
//     */
//    public void setGender(Short gender) {
//        this.gender = gender;
//    }
//
//    /**
//     * 获取
//     *
//     * @return phone
//     */
//    public String getPhone() {
//        return phone;
//    }
//
//    /**
//     * 设置
//     *
//     * @param phone
//     */
//    public void setPhone(String phone) {
//        this.phone = phone;
//    }
//
//    public String toString() {
//        return "User{id = " + id + ", name = " + name + ", age = " + age + ", gender = " + gender + ", phone = " + phone + "}";
//    }
}
