# Generated by Django 4.2.7 on 2023-11-15 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supermarket", "0002_supermarket_delete_supermarketsale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Supermarket",
            new_name="SupermarketSale",
        ),
    ]
