# Generated by Django 4.2.7 on 2023-11-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermarket", "0003_rename_supermarket_supermarketsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="supermarketsale",
            name="invoice_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
